# ref. https://github.com/vegasbrianc/prometheus
version: "3"

services:
  prometheus:
    build:
      context: ./prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/tsdb/data"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/prometheus/consoles"

  grafana:
    image: grafana/grafana:6.4.0
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    links:
      - prometheus
