global:
  scrape_interval: 5s
  scrape_timeout: 1s

scrape_configs:
  - job_name: "prometheus server"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
      
  - job_name: "graylog"
    metrics_path: "/plugins/org.graylog.plugins.metrics.prometheus/metrics"
    basic_auth:
      username: admin
      password: admin
    static_configs:
      - targets: ["graylog:12900"]
  
  - job_name: "elasticsearch"    
    static_configs:
      - targets: ["elasticsearch-exporter:9114"]