version: "3"
services:
  mongo:
    image: mongo:3

  elasticsearch:
    image: elasticsearch:2.3
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

  graylog:    
    build:
      context: .
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_REST_TRANSPORT_URI: http://127.0.0.1:12900
      # GRAYLOG_METRICS_PROMETEHUS_ENABLED: "true"
    volumes:
      - ./data/journal:/usr/share/graylog/data/journal
      # - ./data/config:/usr/share/graylog/data/config
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - 5555:5555
      - 12201:12201/udp
      - 9000:9000      
      - 12900:12900

  prometheus:
    image: prom/prometheus:v2.10.0
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
    ports:
      - 9090:9090
    links:
      - node-exporter
      - graylog
      - elasticsearch-exporter

  node-exporter:
    image: quay.io/prometheus/node-exporter:v0.18.0
    container_name: node-exporter
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs

  grafana:
    image: grafana/grafana:6.7.2
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    links:
      - prometheus

  elasticsearch-exporter:
    image: justwatch/elasticsearch_exporter:1.1.0
    command:
      - "--es.uri=http://elasticsearch:9200"
    ports:
    - 9114:9114
