FROM graylog2/server:2.0.0-1
RUN wget -O /usr/share/graylog/data/plugin/plugin-reporter-prometheus-1.5.0.jar https://github.com/graylog-labs/graylog-plugin-metrics-reporter/releases/download/1.5.0/metrics-reporter-prometheus-1.5.0.jar
