apiVersion: apps/v1
kind: Deployment
metadata:
    name: photoview-deployment

spec:
    replicas: 5
    selector:
        matchLabels:
            app: photo-view

    template:
        metadata:
            labels:
                app: photo-view
                env: stage
        spec:
            containers:
            - image: gcr.io/google-samples/hello-app:1.0
              name: photoview-container
              ports:
                - containerPort: 8080